home: /data/jenkins
main_job_src: service-workflow-config.xml
service_redeploy_src: service-redeploy-config.xml

configs: [
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml", mode: "0777" },
  { src: "sonarqube-config.xml", dir: "/data/jenkins/nodes/sonarqube", file: "config.xml", mode: "0777" },
  { src: "LogParserPublisher.xml", dir: "/data/jenkins", file: "hudson.plugins.logparser.LogParserPublisher.xml", mode: "0777" },
  { src: "parsing_rules", dir: "/data/jenkins", file: "parsing_rules", mode: "0777" },
  { src: "scriptApproval.xml", dir: "/data/jenkins", file: "scriptApproval.xml", mode: "0644" }
]

jobs: [
  {
    name: "go-demo-scale",
    service_name: "go-demo",
    src: "service-scale-df-config.xml",
    scale: "+2",
    time: "45 23 31 12 *"
  }, {
    name: "service-scale",
    service_name: "my-service",
    src: "service-scale-health-config.xml",
    scale: "+1",
  }, {
    name: "go-demo-descale",
    service_name: "go-demo",
    src: "service-scale-df-config.xml",
    scale: "-2",
    time: "15 0 2 1 *"
  }, {
    name: "go-demo-1",
    service_name: "go-demo",
    src: "go-demo-1.xml"
  }, {
    name: "go-demo-2",
    service_name: "go-demo",
    src: "go-demo-2.xml"
  }, {
    name: "go-demo-3",
    service_name: "go-demo",
    src: "go-demo-3.xml"
  }
]
jenkins_plugins: [ ]

jenkins_admin_username: admin
jenkins_admin_password: admin

plugins:
  - ssh-slaves
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
  - template-project
  - maven-plugin
  - dashboard-view
  - sonar
  - active-directory
  - global-build-stats
  - jobConfigHistory
  - build-pipeline-plugin
  - wildfly-deployer


