home: /data/jenkins
main_job_src: service-workflow-config.xml
service_redeploy_src: service-redeploy-config.xml

configs: [
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml", mode: "0777" },
  { src: "sonarquebe-config.xml", dir: "/data/jenkins/nodes/sonarquebe", file: "config.xml", mode: "0777" }, 
  { src: "LogParserPublisher.xml", dir: "/data/jenkins", file: "hudson.plugins.logparser.LogParserPublisher.xml", mode: "0777" },
  { src: "parsing_rules", dir: "/data/jenkins", file: "parsing_rules", mode: "0777" },
  { src: "scriptApproval.xml", dir: "/data/jenkins", file: "scriptApproval.xml", mode: "0644" }
]

jobs: [
  {
    name: "go-demo-1",
    service_name: "go-demo",
    src: "go-demo-1.xml"
  }
]

plugins:
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
  - template-project
  - svn
  - sonarquebe
